<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="DESKTOP-SP8UJ8Q" failures="1" tests="5" name="Test" time="25.572" errors="0" timestamp="2022-08-04T23:42:02 IST">
  <testcase classname="script.Demo1" name="test1" time="2.056">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at script.Demo1.test1(Demo1.java:24)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
  <testcase classname="script.Demo2" name="test2" time="0.012"/>
  <testcase classname="script.Demo2" name="test2" time="0.009"/>
  <testcase classname="script.Demo2" name="test2" time="0.054"/>
  <testcase classname="script.Demo2" name="test2" time="0.013"/>
  <testcase classname="generic.BaseTest" name="@BeforeSuite initReport" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite initReport -->
  <testcase classname="generic.BaseTest" name="@AfterSuite publishReport" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite publishReport -->
</testsuite> <!-- Test -->
